import json
import os
import sys
import io
from contextlib import redirect_stdout

# Ensure we can import engine and config from the parent directory
# We assume this script is in engine/TestvAll/
base_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
if base_dir not in sys.path:
    sys.path.insert(0, base_dir)

import engine
import config

def run_match(name1, path1, name2, path2):
    print(f"Running {name1} vs {name2}...")
    
    # Configure the engine
    # We must update the engine module's globals because it used 'from config import *'
    conf_vars = {
        'PLAYER_1_NAME': name1,
        'PLAYER_1_PATH': path1,
        'PLAYER_2_NAME': name2,
        'PLAYER_2_PATH': path2,
        'GAME_LOG_FILENAME': f'gamelog_{name1}_vs_{name2}',
        'STARTING_GAME_CLOCK': 30.0,
        'BUILD_TIMEOUT': 30.0, 
        'CONNECT_TIMEOUT': 10.0,
        'NUM_ROUNDS': 100,
        'STARTING_STACK': 400,
        'BIG_BLIND': 2,
        'SMALL_BLIND': 1,
        'ENFORCE_GAME_CLOCK': True,
        'PLAYER_LOG_SIZE_LIMIT': 524288
    }
    
    for var, val in conf_vars.items():
        setattr(engine, var, val)
        # Also update config module just in case anything else imports it
        setattr(config, var, val)

    # Change directory to base_dir so relative paths in config work
    old_cwd = os.getcwd()
    os.chdir(base_dir)
    
    output_capture = io.StringIO()
    success = False
    br1, br2 = 0, 0
    
    try:
        with redirect_stdout(output_capture):
            game = engine.Game()
            game.run()
        success = True
    except Exception as e:
        print(f"Error running match {name1} vs {name2}: {e}")
        print(output_capture.getvalue())
    finally:
        os.chdir(old_cwd)

    if success:
        log_path = os.path.join(base_dir, f"{conf_vars['GAME_LOG_FILENAME']}.txt")
        if os.path.exists(log_path):
            with open(log_path, 'r') as f:
                lines = f.readlines()
                for line in reversed(lines):
                    if line.startswith('Final'):
                        try:
                            parts = line.strip().split(', ')
                            def parse_br(p): return int(p.split('(')[1].split(')')[0])
                            br1 = parse_br(parts[1])
                            br2 = parse_br(parts[2])
                            break
                        except Exception as e:
                            print(f"Error parsing final line: {e}")
            # Cleanup
            try:
                os.remove(log_path)
                # Cleanup player log files generated by engine
                p1_log = os.path.join(base_dir, f"{name1}.txt")
                p2_log = os.path.join(base_dir, f"{name2}.txt")
                if os.path.exists(p1_log): os.remove(p1_log)
                if os.path.exists(p2_log): os.remove(p2_log)
            except Exception as e:
                print(f"Error during cleanup: {e}")
        else:
            print(f"Log file not found for {name1} vs {name2}")
            print(output_capture.getvalue())
    
    return br1, br2

def main():
    # Load bots relative to this script's location
    script_dir = os.path.dirname(os.path.abspath(__file__))
    bots_json_path = os.path.join(script_dir, 'bots.json')
    
    if not os.path.exists(bots_json_path):
        print(f"Error: {bots_json_path} not found.")
        return

    with open(bots_json_path, 'r') as f:
        bots = json.load(f)
    
    bot_names = list(bots.keys())
    results = {}

    for i in range(len(bot_names)):
        for j in range(i + 1, len(bot_names)):
            name1 = bot_names[i]
            path1 = bots[name1]
            name2 = bot_names[j]
            path2 = bots[name2]
            
            br1, br2 = run_match(name1, path1, name2, path2)
            match_key = f"{name1}_vs_{name2}"
            results[match_key] = {
                name1: br1,
                name2: br2
            }
            print(f"  Result: {name1}: {br1}, {name2}: {br2}")

    results_path = os.path.join(script_dir, 'results.json')
    with open(results_path, 'w') as f:
        json.dump(results, f, indent=4)
    print(f"Comparison complete. Results saved to {results_path}")

if __name__ == "__main__":
    main()